import { type Option } from "@src/types";

export const institutos: Option[] = [
  { value: "7", label: "instituto de biotecnología" },
  { value: "9", label: "instituto de salud comunitaria" },
  { value: "13", label: "instituto de educación" },
  { value: "21", label: "instituto de tecnología e ingeniería" },
  { value: "33", label: "curso de preparación universitaria" },
  { value: "34", label: "eventos" },
  { value: "39", label: "materias unahur" },
  { value: "41", label: "rectorado" },
  { value: "42", label: "cultura" },
  { value: "43", label: "escuela secundaria" },
  { value: "44", label: "escuela de inglés" },
  { value: "45", label: "deportes" },
  { value: "46", label: "upami" },
  { value: "47", label: "gestión estudiantil" },
  { value: "48", label: "nuevos entornos y lenguajes" },
  { value: "49", label: "inglés 1 y 2 (todas las carreras)" },
  { value: "50", label: "posgrado" },
  { value: "51", label: "programación común a todas las carreras" },
  { value: "52", label: "secretaría académica" },
  { value: "53", label: "centro de formación para el trabajo" },
];

export const horas: Option[] = [
  { value: "09:00", label: "09:00" },
  { value: "10:00", label: "10:00" },
  { value: "11:00", label: "11:00" },
  { value: "12:00", label: "12:00" },
  { value: "13:00", label: "13:00" },
  { value: "14:00", label: "14:00" },
  { value: "15:00", label: "15:00" },
  { value: "16:00", label: "16:00" },
  { value: "17:00", label: "17:00" },
  { value: "18:00", label: "18:00" },
  { value: "19:00", label: "19:00" },
  { value: "20:00", label: "20:00" },
  { value: "21:00", label: "21:00" },
  { value: "22:00", label: "22:00" },
];
